# Generated by Django 5.2.15 on 2026-06-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encryptednote',
            name='title',
            field=models.CharField(default='Untitled', max_length=255),
        ),
        migrations.AlterField(
            model_name='encryptednote',
            name='ciphertext',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='encryptednote',
            name='nonce',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='encryptednote',
            name='salt',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='notebookfolder',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
