# Generated by Django 5.2.15 on 2026-06-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_encryptednote_title_alter_encryptednote_ciphertext_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebookfolder',
            name='anonymous_create',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notebookfolder',
            name='anonymous_edit',
            field=models.BooleanField(default=False),
        ),
    ]
