# Generated by Django 5.2.15 on 2026-06-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0003_notebookfolder_anonymous_create_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encryptednote',
            name='anonymous_edit',
            field=models.BooleanField(default=True),
        ),
    ]
